apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chariot-hub.fullname" . }}
  labels:
    {{- include "chariot-hub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chariot-hub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chariot-hub.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: hub
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: SHARED_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.env.existingSecret | default (include "chariot-hub.fullname" . ) }}
              key: sharedSecret
        - name: NODE_ENV
          value: "production"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
