{{- if not .Values.env.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chariot-hub.fullname" . }}
  labels:
    {{- include "chariot-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  sharedSecret: {{ .Values.env.sharedSecret | quote }}
  {{- if .Values.auth.enabled }}
  authSecret: {{ .Values.auth.secret | quote }}
  {{- end }}
{{- end }}
