{{- if not .Values.hub.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chariot-agent.fullname" . }}-hub-secret
  labels:
    {{- include "chariot-agent.labels" . | nindent 4 }}
type: Opaque
data:
  sharedSecret: {{ .Values.hub.sharedSecret | b64enc | quote }}
{{- end }}
